apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    name: traffic-generator
spec:
  containers:
    - name: traffic-generator
      image: koreng24/traffic-generator:1.0.0
      args:
        - 'color-svc/api?colorKey=primary'
        - '0.5'
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '300m'
